begin;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'movements' and column_name = 'spent_by'
  ) then
    raise exception 'La actualización V3 ya está aplicada. No vuelvas a ejecutar migration_integrity_v2.sql.';
  end if;
end
$$;

-- Only the users that already exist when this migration runs become partners.
-- Before running it, confirm that Authentication > Users contains only the
-- two accounts authorized by Fernández Conde, S.C.
create table if not exists public.partners (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  display_name text not null default '',
  created_at timestamptz not null default now()
);

do $$
declare
  v_partner_count integer;
  v_user_count integer;
begin
  select count(*) into v_partner_count from public.partners;
  if v_partner_count = 0 then
    select count(*) into v_user_count from auth.users;
    if v_user_count <> 2 then
      raise exception 'La instalación requiere exactamente dos usuarios en Authentication > Users; se encontraron %.', v_user_count;
    end if;
    insert into public.partners (user_id, email, display_name)
    select
      id,
      coalesce(email, ''),
      coalesce(nullif(raw_user_meta_data ->> 'name', ''), split_part(coalesce(email, ''), '@', 1))
    from auth.users;
  elsif v_partner_count <> 2 then
    raise exception 'La tabla partners debe contener exactamente dos socios; se encontraron %.', v_partner_count;
  end if;
end
$$;

alter table public.partners enable row level security;

create or replace function public.is_finance_partner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.partners where user_id = auth.uid()
  );
$$;

revoke all on function public.is_finance_partner() from public;
grant execute on function public.is_finance_partner() to authenticated;

drop policy if exists "Socios consultan directorio" on public.partners;
create policy "Socios consultan directorio"
on public.partners for select to authenticated
using (public.is_finance_partner());

alter table public.clients
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by uuid references auth.users(id) on delete set null default auth.uid(),
  add column if not exists updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table public.documents
  add column if not exists client_request_id uuid,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by uuid references auth.users(id) on delete set null default auth.uid(),
  add column if not exists updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table public.movements
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by uuid references auth.users(id) on delete set null default auth.uid(),
  add column if not exists updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'documents_client_request_id_key'
      and conrelid = 'public.documents'::regclass
  ) then
    alter table public.documents
      add constraint documents_client_request_id_key unique (client_request_id);
  end if;
end
$$;

create table if not exists public.finance_audit_log (
  id bigint generated by default as identity primary key,
  entity text not null check (entity in ('client','document','movement')),
  record_id bigint not null,
  action text not null check (action in ('created','updated','trashed','restored')),
  actor_id uuid references auth.users(id) on delete set null default auth.uid(),
  snapshot jsonb not null,
  occurred_at timestamptz not null default now()
);

alter table public.finance_audit_log enable row level security;
drop policy if exists "Socios consultan bitacora" on public.finance_audit_log;
create policy "Socios consultan bitacora"
on public.finance_audit_log for select to authenticated
using (public.is_finance_partner());

create or replace function public.touch_finance_record()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  if old.deleted_at is null and new.deleted_at is not null then
    new.deleted_by := auth.uid();
  elsif old.deleted_at is not null and new.deleted_at is null then
    new.deleted_by := null;
  end if;
  return new;
end;
$$;

create or replace function public.log_finance_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entity text;
  v_action text;
begin
  v_entity := case tg_table_name
    when 'clients' then 'client'
    when 'documents' then 'document'
    else 'movement'
  end;

  if tg_op = 'INSERT' then
    v_action := 'created';
  elsif old.deleted_at is null and new.deleted_at is not null then
    v_action := 'trashed';
  elsif old.deleted_at is not null and new.deleted_at is null then
    v_action := 'restored';
  else
    v_action := 'updated';
  end if;

  insert into public.finance_audit_log (entity, record_id, action, actor_id, snapshot)
  values (v_entity, new.id, v_action, auth.uid(), to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists clients_touch_record on public.clients;
create trigger clients_touch_record before update on public.clients
for each row execute function public.touch_finance_record();
drop trigger if exists documents_touch_record on public.documents;
create trigger documents_touch_record before update on public.documents
for each row execute function public.touch_finance_record();
drop trigger if exists movements_touch_record on public.movements;
create trigger movements_touch_record before update on public.movements
for each row execute function public.touch_finance_record();

drop trigger if exists clients_audit_record on public.clients;
create trigger clients_audit_record after insert or update on public.clients
for each row execute function public.log_finance_change();
drop trigger if exists documents_audit_record on public.documents;
create trigger documents_audit_record after insert or update on public.documents
for each row execute function public.log_finance_change();
drop trigger if exists movements_audit_record on public.movements;
create trigger movements_audit_record after insert or update on public.movements
for each row execute function public.log_finance_change();

drop policy if exists "Socios administran clientes" on public.clients;
drop policy if exists "Socios administran documentos" on public.documents;
drop policy if exists "Socios administran movimientos" on public.movements;

drop policy if exists "Socios leen clientes" on public.clients;
drop policy if exists "Socios crean clientes" on public.clients;
drop policy if exists "Socios actualizan clientes" on public.clients;
create policy "Socios leen clientes" on public.clients
for select to authenticated using (public.is_finance_partner());
create policy "Socios crean clientes" on public.clients
for insert to authenticated with check (public.is_finance_partner());
create policy "Socios actualizan clientes" on public.clients
for update to authenticated
using (public.is_finance_partner()) with check (public.is_finance_partner());

drop policy if exists "Socios leen documentos" on public.documents;
drop policy if exists "Socios crean documentos" on public.documents;
drop policy if exists "Socios actualizan documentos" on public.documents;
create policy "Socios leen documentos" on public.documents
for select to authenticated using (public.is_finance_partner());
create policy "Socios crean documentos" on public.documents
for insert to authenticated with check (public.is_finance_partner());
create policy "Socios actualizan documentos" on public.documents
for update to authenticated
using (public.is_finance_partner()) with check (public.is_finance_partner());

drop policy if exists "Socios leen movimientos" on public.movements;
drop policy if exists "Socios crean movimientos" on public.movements;
drop policy if exists "Socios actualizan movimientos" on public.movements;
create policy "Socios leen movimientos" on public.movements
for select to authenticated using (public.is_finance_partner());
create policy "Socios crean movimientos" on public.movements
for insert to authenticated with check (public.is_finance_partner());
create policy "Socios actualizan movimientos" on public.movements
for update to authenticated
using (public.is_finance_partner()) with check (public.is_finance_partner());

grant select on public.partners, public.finance_audit_log to authenticated;
grant select, insert, update on public.clients, public.documents, public.movements to authenticated;
revoke delete on public.clients, public.documents, public.movements from authenticated;

create or replace function public.create_finance_document(
  p_kind text,
  p_client_id bigint,
  p_concept text,
  p_amount_cents bigint,
  p_status text,
  p_notes text,
  p_request_id uuid
)
returns table (id bigint, folio text, issued_at timestamptz, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_folio text;
  v_issued_at timestamptz;
  v_updated_at timestamptz;
  v_prefix text;
begin
  if not public.is_finance_partner() then
    raise exception 'Tu cuenta no está autorizada para administrar la firma.';
  end if;
  if p_request_id is null then
    raise exception 'Falta el identificador de la operación.';
  end if;
  if p_amount_cents < 0 then
    raise exception 'El importe no puede ser negativo.';
  end if;
  if not exists (select 1 from public.clients c where c.id = p_client_id and c.deleted_at is null) then
    raise exception 'El cliente ya no existe o se encuentra en la papelera.';
  end if;

  select d.id, d.folio, d.issued_at, d.updated_at
  into v_id, v_folio, v_issued_at, v_updated_at
  from public.documents d
  where d.client_request_id = p_request_id;

  if found then
    return query select v_id, v_folio, v_issued_at, v_updated_at;
    return;
  end if;

  v_prefix := case p_kind
    when 'Presupuesto' then 'PRE'
    when 'Recibo' then 'REC'
    when 'Cuenta de cobro' then 'COB'
    else null
  end;
  if v_prefix is null then
    raise exception 'Tipo de documento no válido.';
  end if;

  v_id := nextval(pg_get_serial_sequence('public.documents', 'id'));
  v_folio := v_prefix || '-' || lpad(v_id::text, 4, '0');

  insert into public.documents (
    id, folio, kind, client_id, concept, amount_cents, status, notes, client_request_id
  ) values (
    v_id, v_folio, p_kind, p_client_id, trim(p_concept), p_amount_cents,
    p_status, coalesce(p_notes, ''), p_request_id
  )
  on conflict (client_request_id) do nothing
  returning documents.issued_at, documents.updated_at
  into v_issued_at, v_updated_at;

  if not found then
    select d.id, d.folio, d.issued_at, d.updated_at
    into v_id, v_folio, v_issued_at, v_updated_at
    from public.documents d
    where d.client_request_id = p_request_id;
    return query select v_id, v_folio, v_issued_at, v_updated_at;
    return;
  end if;

  if p_status = 'Pagado' then
    insert into public.movements (
      type, category, description, amount_cents, document_id
    ) values (
      'Ingreso', 'Honorarios', trim(p_concept), p_amount_cents, v_id
    );
  end if;

  return query select v_id, v_folio, v_issued_at, v_updated_at;
end;
$$;

create or replace function public.update_finance_document(
  p_id bigint,
  p_kind text,
  p_client_id bigint,
  p_concept text,
  p_amount_cents bigint,
  p_status text,
  p_notes text,
  p_expected_updated_at timestamptz
)
returns table (updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_document public.documents%rowtype;
  v_updated_at timestamptz;
begin
  if not public.is_finance_partner() then
    raise exception 'Tu cuenta no está autorizada para administrar la firma.';
  end if;
  select * into v_document from public.documents
  where documents.id = p_id and deleted_at is null
  for update;
  if not found then
    raise exception 'Este documento ya no existe o fue enviado a la papelera.';
  end if;
  if p_expected_updated_at is not null and v_document.updated_at <> p_expected_updated_at then
    raise exception 'Este documento fue modificado por tu socio. Actualiza la información antes de volver a editarlo.';
  end if;
  if not exists (select 1 from public.clients c where c.id = p_client_id and c.deleted_at is null) then
    raise exception 'El cliente ya no existe o se encuentra en la papelera.';
  end if;

  update public.documents
  set kind = p_kind,
      client_id = p_client_id,
      concept = trim(p_concept),
      amount_cents = p_amount_cents,
      status = p_status,
      notes = coalesce(p_notes, '')
  where documents.id = p_id
  returning documents.updated_at into v_updated_at;

  if p_status = 'Pagado' then
    insert into public.movements (
      type, category, description, amount_cents, document_id
    ) values (
      'Ingreso', 'Honorarios', trim(p_concept), p_amount_cents, p_id
    )
    on conflict (document_id) where document_id is not null
    do update set
      description = excluded.description,
      amount_cents = excluded.amount_cents,
      deleted_at = null,
      deleted_by = null;
  else
    update public.movements
    set deleted_at = coalesce(deleted_at, now()),
        deleted_by = case when deleted_at is null then auth.uid() else deleted_by end
    where document_id = p_id and deleted_at is null;
  end if;

  return query select v_updated_at;
end;
$$;

create or replace function public.mark_finance_document_paid(
  p_id bigint,
  p_expected_updated_at timestamptz
)
returns table (updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_document public.documents%rowtype;
  v_updated_at timestamptz;
begin
  if not public.is_finance_partner() then
    raise exception 'Tu cuenta no está autorizada para administrar la firma.';
  end if;
  select * into v_document from public.documents
  where documents.id = p_id and deleted_at is null
  for update;
  if not found then
    raise exception 'Este documento ya no existe o fue enviado a la papelera.';
  end if;
  if p_expected_updated_at is not null and v_document.updated_at <> p_expected_updated_at then
    raise exception 'Este documento fue modificado por tu socio. Actualiza la información antes de registrar el pago.';
  end if;

  update public.documents set status = 'Pagado'
  where documents.id = p_id
  returning documents.updated_at into v_updated_at;

  insert into public.movements (type, category, description, amount_cents, document_id)
  values ('Ingreso', 'Honorarios', v_document.concept, v_document.amount_cents, p_id)
  on conflict (document_id) where document_id is not null
  do update set
    description = excluded.description,
    amount_cents = excluded.amount_cents,
    deleted_at = null,
    deleted_by = null;

  return query select v_updated_at;
end;
$$;

create or replace function public.set_finance_record_trashed(
  p_entity text,
  p_id bigint,
  p_expected_updated_at timestamptz,
  p_trashed boolean
)
returns table (updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_updated_at timestamptz;
  v_status text;
  v_client_id bigint;
  v_concept text;
  v_amount_cents bigint;
  v_updated_at timestamptz;
begin
  if not public.is_finance_partner() then
    raise exception 'Tu cuenta no está autorizada para administrar la firma.';
  end if;

  if p_entity = 'client' then
    select clients.updated_at into v_current_updated_at
    from public.clients where clients.id = p_id for update;
    if not found then raise exception 'El cliente ya no existe.'; end if;
    if p_expected_updated_at is not null and v_current_updated_at <> p_expected_updated_at then
      raise exception 'Este cliente fue modificado por tu socio. Actualiza la información antes de continuar.';
    end if;
    if p_trashed and exists (
      select 1 from public.documents d where d.client_id = p_id and d.deleted_at is null
    ) then
      raise exception 'No puedes enviar este cliente a la papelera porque tiene documentos activos.';
    end if;
    update public.clients
    set deleted_at = case when p_trashed then now() else null end,
        deleted_by = case when p_trashed then auth.uid() else null end
    where clients.id = p_id
    returning clients.updated_at into v_updated_at;

  elsif p_entity = 'document' then
    select documents.updated_at, documents.status, documents.client_id, documents.concept, documents.amount_cents
    into v_current_updated_at, v_status, v_client_id, v_concept, v_amount_cents
    from public.documents where documents.id = p_id for update;
    if not found then raise exception 'El documento ya no existe.'; end if;
    if p_expected_updated_at is not null and v_current_updated_at <> p_expected_updated_at then
      raise exception 'Este documento fue modificado por tu socio. Actualiza la información antes de continuar.';
    end if;
    if not p_trashed and not exists (
      select 1 from public.clients c where c.id = v_client_id and c.deleted_at is null
    ) then
      raise exception 'Restaura primero al cliente relacionado con este documento.';
    end if;
    update public.documents
    set deleted_at = case when p_trashed then now() else null end,
        deleted_by = case when p_trashed then auth.uid() else null end
    where documents.id = p_id
    returning documents.updated_at into v_updated_at;

    if p_trashed then
      update public.movements
      set deleted_at = coalesce(deleted_at, now()),
          deleted_by = case when deleted_at is null then auth.uid() else deleted_by end
      where document_id = p_id and deleted_at is null;
    elsif v_status = 'Pagado' then
      insert into public.movements (type, category, description, amount_cents, document_id)
      values ('Ingreso', 'Honorarios', v_concept, v_amount_cents, p_id)
      on conflict (document_id) where document_id is not null
      do update set
        description = excluded.description,
        amount_cents = excluded.amount_cents,
        deleted_at = null,
        deleted_by = null;
    end if;

  elsif p_entity = 'movement' then
    select movements.updated_at into v_current_updated_at
    from public.movements
    where movements.id = p_id and movements.document_id is null
    for update;
    if not found then raise exception 'El gasto ya no existe o pertenece a un documento.'; end if;
    if p_expected_updated_at is not null and v_current_updated_at <> p_expected_updated_at then
      raise exception 'Este gasto fue modificado por tu socio. Actualiza la información antes de continuar.';
    end if;
    update public.movements
    set deleted_at = case when p_trashed then now() else null end,
        deleted_by = case when p_trashed then auth.uid() else null end
    where movements.id = p_id
    returning movements.updated_at into v_updated_at;
  else
    raise exception 'Tipo de registro no válido.';
  end if;

  return query select v_updated_at;
end;
$$;

revoke all on function public.create_finance_document(text,bigint,text,bigint,text,text,uuid) from public;
revoke all on function public.update_finance_document(bigint,text,bigint,text,bigint,text,text,timestamptz) from public;
revoke all on function public.mark_finance_document_paid(bigint,timestamptz) from public;
revoke all on function public.set_finance_record_trashed(text,bigint,timestamptz,boolean) from public;
grant execute on function public.create_finance_document(text,bigint,text,bigint,text,text,uuid) to authenticated;
grant execute on function public.update_finance_document(bigint,text,bigint,text,bigint,text,text,timestamptz) to authenticated;
grant execute on function public.mark_finance_document_paid(bigint,timestamptz) to authenticated;
grant execute on function public.set_finance_record_trashed(text,bigint,timestamptz,boolean) to authenticated;

commit;
