begin;

-- V6 is only valid for the two authorized partners already registered.
do $$
declare
  v_partner_count integer;
begin
  select count(*) into v_partner_count from public.partners;
  if v_partner_count <> 2 then
    raise exception 'La actualización V6 requiere exactamente dos socios autorizados; se encontraron %.', v_partner_count;
  end if;
end
$$;

-- Derived margins. Expenses only affect a matter when they are explicitly
-- linked to its document_id. Deleted records are excluded.
create or replace view public.finance_document_margins_v6
with (security_invoker = true)
as
with totals as (
  select
    d.id as document_id,
    d.client_id,
    d.folio,
    d.concept,
    coalesce(sum(m.amount_cents) filter (where m.type = 'Ingreso'), 0)::bigint as income_cents,
    coalesce(sum(m.amount_cents) filter (where m.type = 'Gasto'), 0)::bigint as expense_cents
  from public.documents d
  left join public.movements m
    on m.document_id = d.id
   and m.deleted_at is null
  where d.deleted_at is null
  group by d.id, d.client_id, d.folio, d.concept
)
select
  document_id,
  client_id,
  folio,
  concept,
  income_cents,
  expense_cents,
  income_cents - expense_cents as margin_cents,
  case
    when income_cents = 0 then null
    else round(((income_cents - expense_cents)::numeric / income_cents::numeric) * 100, 2)
  end as margin_percent
from totals;

create or replace view public.finance_client_margins_v6
with (security_invoker = true)
as
with totals as (
  select
    c.id as client_id,
    c.name as client_name,
    coalesce(sum(dm.income_cents), 0)::bigint as income_cents,
    coalesce(sum(dm.expense_cents), 0)::bigint as expense_cents
  from public.clients c
  left join public.finance_document_margins_v6 dm on dm.client_id = c.id
  where c.deleted_at is null
  group by c.id, c.name
)
select
  client_id,
  client_name,
  income_cents,
  expense_cents,
  income_cents - expense_cents as margin_cents,
  case
    when income_cents = 0 then null
    else round(((income_cents - expense_cents)::numeric / income_cents::numeric) * 100, 2)
  end as margin_percent
from totals;

grant select on public.finance_document_margins_v6, public.finance_client_margins_v6 to authenticated;

-- Configuration uses basis points: 10000 = 100.00%.
create table public.profit_distribution_settings_v6 (
  id boolean primary key default true check (id),
  fund_bps integer not null default 2000 check (fund_bps between 0 and 10000),
  oscar_bps integer not null default 4000 check (oscar_bps between 0 and 10000),
  dan_bps integer not null default 4000 check (dan_bps between 0 and 10000),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  constraint profit_distribution_settings_v6_total_check
    check (fund_bps + oscar_bps + dan_bps = 10000)
);

insert into public.profit_distribution_settings_v6 (id, fund_bps, oscar_bps, dan_bps)
values (true, 2000, 4000, 4000)
on conflict (id) do nothing;

create table public.profit_distributions_v6 (
  id bigint generated by default as identity primary key,
  period_start date not null,
  period_end date not null check (period_end >= period_start),
  income_cents bigint not null check (income_cents >= 0),
  expense_cents bigint not null check (expense_cents >= 0),
  net_profit_cents bigint not null check (net_profit_cents > 0),
  fund_cents bigint not null check (fund_cents >= 0),
  oscar_cents bigint not null check (oscar_cents >= 0),
  dan_cents bigint not null check (dan_cents >= 0),
  fund_bps integer not null,
  oscar_bps integer not null,
  dan_bps integer not null,
  client_request_id uuid not null unique,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  constraint profit_distributions_v6_amounts_check
    check (fund_cents + oscar_cents + dan_cents = net_profit_cents),
  constraint profit_distributions_v6_percentages_check
    check (fund_bps + oscar_bps + dan_bps = 10000)
);

alter table public.profit_distribution_settings_v6 enable row level security;
alter table public.profit_distributions_v6 enable row level security;

create policy "Socios consultan configuracion V6"
on public.profit_distribution_settings_v6 for select to authenticated
using (public.is_finance_partner());

create policy "Socios consultan repartos V6"
on public.profit_distributions_v6 for select to authenticated
using (public.is_finance_partner());

grant select on public.profit_distribution_settings_v6, public.profit_distributions_v6 to authenticated;
revoke insert, update, delete on public.profit_distribution_settings_v6, public.profit_distributions_v6 from authenticated, anon;

create or replace view public.finance_fund_balance_v6
with (security_invoker = true)
as
select coalesce(sum(fund_cents), 0)::bigint as balance_cents
from public.profit_distributions_v6;

grant select on public.finance_fund_balance_v6 to authenticated;

create or replace function public.update_profit_distribution_settings_v6(
  p_fund_bps integer,
  p_oscar_bps integer,
  p_dan_bps integer
)
returns setof public.profit_distribution_settings_v6
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.profit_distribution_settings_v6%rowtype;
begin
  if not public.is_finance_partner() then
    raise exception 'Tu cuenta no está autorizada para administrar la firma.';
  end if;
  if p_fund_bps is null or p_oscar_bps is null or p_dan_bps is null
     or p_fund_bps < 0 or p_oscar_bps < 0 or p_dan_bps < 0
     or p_fund_bps + p_oscar_bps + p_dan_bps <> 10000 then
    raise exception 'Los porcentajes de Fondo, Oscar y Dan deben ser positivos y sumar 100%%.';
  end if;

  update public.profit_distribution_settings_v6
  set fund_bps = p_fund_bps,
      oscar_bps = p_oscar_bps,
      dan_bps = p_dan_bps,
      updated_at = now(),
      updated_by = auth.uid()
  where id = true
  returning * into v_row;
  return next v_row;
end;
$$;

-- The settings row is locked while a distribution is calculated. This also
-- serializes overlap checks and prevents the same income period being shared twice.
create or replace function public.create_profit_distribution_v6(
  p_period_start date,
  p_period_end date,
  p_request_id uuid
)
returns setof public.profit_distributions_v6
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings public.profit_distribution_settings_v6%rowtype;
  v_row public.profit_distributions_v6%rowtype;
  v_income_cents bigint;
  v_expense_cents bigint;
  v_net_profit_cents bigint;
  v_fund_cents bigint;
  v_oscar_cents bigint;
  v_dan_cents bigint;
begin
  if not public.is_finance_partner() then
    raise exception 'Tu cuenta no está autorizada para administrar la firma.';
  end if;
  if p_request_id is null then raise exception 'Falta el identificador de la operación.'; end if;
  if p_period_start is null or p_period_end is null or p_period_end < p_period_start then
    raise exception 'El periodo del reparto no es válido.';
  end if;

  select * into v_row
  from public.profit_distributions_v6
  where client_request_id = p_request_id;
  if found then return next v_row; return; end if;

  select * into v_settings
  from public.profit_distribution_settings_v6
  where id = true
  for update;

  if exists (
    select 1 from public.profit_distributions_v6 d
    where daterange(d.period_start, d.period_end, '[]') && daterange(p_period_start, p_period_end, '[]')
  ) then
    raise exception 'Este periodo se cruza con un reparto ya guardado.';
  end if;

  select
    coalesce(sum(amount_cents) filter (where type = 'Ingreso'), 0)::bigint,
    coalesce(sum(amount_cents) filter (where type = 'Gasto'), 0)::bigint
  into v_income_cents, v_expense_cents
  from public.movements
  where deleted_at is null
    and (occurred_at at time zone 'America/Mexico_City')::date between p_period_start and p_period_end;

  v_net_profit_cents := v_income_cents - v_expense_cents;
  if v_net_profit_cents <= 0 then
    raise exception 'El periodo no tiene una utilidad neta positiva para repartir.';
  end if;

  v_fund_cents := round(v_net_profit_cents::numeric * v_settings.fund_bps / 10000)::bigint;
  v_oscar_cents := round(v_net_profit_cents::numeric * v_settings.oscar_bps / 10000)::bigint;
  v_dan_cents := v_net_profit_cents - v_fund_cents - v_oscar_cents;

  insert into public.profit_distributions_v6 (
    period_start, period_end, income_cents, expense_cents, net_profit_cents,
    fund_cents, oscar_cents, dan_cents, fund_bps, oscar_bps, dan_bps,
    client_request_id, created_by
  ) values (
    p_period_start, p_period_end, v_income_cents, v_expense_cents, v_net_profit_cents,
    v_fund_cents, v_oscar_cents, v_dan_cents,
    v_settings.fund_bps, v_settings.oscar_bps, v_settings.dan_bps,
    p_request_id, auth.uid()
  )
  returning * into v_row;
  return next v_row;
end;
$$;

-- V6 expense RPCs can optionally attribute a cost to a document/matter.
create or replace function public.create_finance_expense_v6(
  p_category text,
  p_description text,
  p_amount_cents bigint,
  p_spent_by text,
  p_occurred_at timestamptz,
  p_document_id bigint,
  p_request_id uuid
)
returns setof public.movements
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.movements%rowtype;
begin
  if not public.is_finance_partner() then raise exception 'Tu cuenta no está autorizada para administrar la firma.'; end if;
  if p_request_id is null then raise exception 'Falta el identificador de la operación.'; end if;
  if p_amount_cents <= 0 then raise exception 'El importe debe ser mayor que cero.'; end if;
  if trim(coalesce(p_description, '')) = '' then raise exception 'Escribe la descripción del gasto.'; end if;
  if p_spent_by not in ('Oscar', 'Dan') then raise exception 'Selecciona quién realizó el gasto.'; end if;
  if p_document_id is not null and not exists (
    select 1 from public.documents where id = p_document_id and deleted_at is null
  ) then raise exception 'El presupuesto seleccionado ya no existe o está en la papelera.'; end if;

  select * into v_row from public.movements where client_request_id = p_request_id;
  if found then
    if v_row.type <> 'Gasto' then raise exception 'El identificador de operación ya pertenece a otro movimiento.'; end if;
    return next v_row; return;
  end if;

  insert into public.movements (
    type, category, description, amount_cents, spent_by, occurred_at,
    document_id, client_request_id
  ) values (
    'Gasto', trim(p_category), trim(p_description), p_amount_cents,
    p_spent_by, coalesce(p_occurred_at, now()), p_document_id, p_request_id
  )
  on conflict (client_request_id) where client_request_id is not null do nothing
  returning * into v_row;

  if not found then select * into v_row from public.movements where client_request_id = p_request_id; end if;
  return next v_row;
end;
$$;

create or replace function public.update_finance_expense_v6(
  p_id bigint,
  p_category text,
  p_description text,
  p_amount_cents bigint,
  p_spent_by text,
  p_occurred_at timestamptz,
  p_document_id bigint,
  p_expected_updated_at timestamptz
)
returns setof public.movements
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.movements%rowtype;
begin
  if not public.is_finance_partner() then raise exception 'Tu cuenta no está autorizada para administrar la firma.'; end if;
  if p_amount_cents <= 0 then raise exception 'El importe debe ser mayor que cero.'; end if;
  if trim(coalesce(p_description, '')) = '' then raise exception 'Escribe la descripción del gasto.'; end if;
  if p_spent_by not in ('Oscar', 'Dan') then raise exception 'Selecciona quién realizó el gasto.'; end if;
  if p_document_id is not null and not exists (
    select 1 from public.documents where id = p_document_id and deleted_at is null
  ) then raise exception 'El presupuesto seleccionado ya no existe o está en la papelera.'; end if;

  select * into v_row from public.movements
  where id = p_id and type = 'Gasto' and deleted_at is null
  for update;
  if not found then raise exception 'Este gasto ya no existe o fue enviado a la papelera.'; end if;
  if p_expected_updated_at is not null and v_row.updated_at <> p_expected_updated_at then
    raise exception 'Este gasto fue modificado por tu socio. Actualiza la información antes de editarlo.';
  end if;

  update public.movements
  set category = trim(p_category),
      description = trim(p_description),
      amount_cents = p_amount_cents,
      spent_by = p_spent_by,
      occurred_at = coalesce(p_occurred_at, occurred_at),
      document_id = p_document_id
  where id = p_id
  returning * into v_row;
  return next v_row;
end;
$$;

-- Publicly callable read-only heartbeat. It exposes no partner data.
create or replace function public.finance_keep_alive_v6()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select true;
$$;

revoke all on function public.update_profit_distribution_settings_v6(integer, integer, integer) from public, anon;
revoke all on function public.create_profit_distribution_v6(date, date, uuid) from public, anon;
revoke all on function public.create_finance_expense_v6(text, text, bigint, text, timestamptz, bigint, uuid) from public, anon;
revoke all on function public.update_finance_expense_v6(bigint, text, text, bigint, text, timestamptz, bigint, timestamptz) from public, anon;
revoke all on function public.finance_keep_alive_v6() from public;

grant execute on function public.update_profit_distribution_settings_v6(integer, integer, integer) to authenticated;
grant execute on function public.create_profit_distribution_v6(date, date, uuid) to authenticated;
grant execute on function public.create_finance_expense_v6(text, text, bigint, text, timestamptz, bigint, uuid) to authenticated;
grant execute on function public.update_finance_expense_v6(bigint, text, text, bigint, text, timestamptz, bigint, timestamptz) to authenticated;
grant execute on function public.finance_keep_alive_v6() to anon, authenticated;

commit;
