begin;

-- V8 sólo puede aplicarse al proyecto cerrado de los dos socios autorizados.
do $$
declare
  v_partner_count integer;
begin
  select count(*) into v_partner_count from public.partners;
  if v_partner_count <> 2 then
    raise exception 'La actualización V8 requiere exactamente dos socios autorizados; se encontraron %.', v_partner_count;
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'clients' and column_name = 'practice_area'
  ) or to_regclass('public.case_stage_templates_v8') is not null
    or to_regclass('public.case_stage_steps_v8') is not null
    or to_regclass('public.client_case_stage_progress_v8') is not null then
    raise exception 'La actualización V8 ya está aplicada o quedó parcialmente instalada. Revisa antes de volver a ejecutarla.';
  end if;
end
$$;

-- El área es opcional y no tiene valor predeterminado: los clientes actuales
-- permanecen sin clasificar hasta que un socio los edite manualmente.
alter table public.clients
  add column practice_area text;

alter table public.clients
  add constraint clients_practice_area_v8_check
  check (practice_area in ('Migratorio/COMAR', 'Arrendamiento', 'Civil', 'Otro'));

-- Una plantilla pertenece a un área. Agregar Arrendamiento o Civil después
-- sólo requerirá insertar una plantilla y sus etapas.
create table public.case_stage_templates_v8 (
  id bigint generated by default as identity primary key,
  practice_area text not null unique,
  name text not null,
  created_at timestamptz not null default now(),
  constraint case_stage_templates_v8_area_check
    check (practice_area in ('Migratorio/COMAR', 'Arrendamiento', 'Civil', 'Otro')),
  constraint case_stage_templates_v8_name_check check (btrim(name) <> '')
);

create table public.case_stage_steps_v8 (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.case_stage_templates_v8(id) on delete cascade,
  name text not null,
  group_name text not null,
  group_order integer not null check (group_order > 0),
  step_order integer not null check (step_order > 0),
  created_at timestamptz not null default now(),
  constraint case_stage_steps_v8_name_check check (btrim(name) <> ''),
  constraint case_stage_steps_v8_group_check check (btrim(group_name) <> ''),
  constraint case_stage_steps_v8_template_order_key unique (template_id, step_order),
  constraint case_stage_steps_v8_template_name_key unique (template_id, name)
);

create table public.client_case_stage_progress_v8 (
  client_id bigint not null references public.clients(id) on delete cascade,
  step_id bigint not null references public.case_stage_steps_v8(id) on delete cascade,
  completed boolean not null default false,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null default auth.uid(),
  primary key (client_id, step_id)
);

create index client_case_stage_progress_v8_step_id_idx
  on public.client_case_stage_progress_v8 (step_id);
create index client_case_stage_progress_v8_changed_by_idx
  on public.client_case_stage_progress_v8 (changed_by);

insert into public.case_stage_templates_v8 (practice_area, name)
values ('Migratorio/COMAR', 'Seguimiento COMAR');

insert into public.case_stage_steps_v8 (
  template_id, name, group_name, group_order, step_order
)
select template.id, seed.name, seed.group_name, seed.group_order, seed.step_order
from public.case_stage_templates_v8 template
cross join (values
  ('Solicitud', 'Trámite ante COMAR', 1, 1),
  ('Cita en Naucalpan (COMAR 1)', 'Trámite ante COMAR', 1, 2),
  ('Citas de admisión', 'Trámite ante COMAR', 1, 3),
  ('Entrevista de elegibilidad', 'Trámite ante COMAR', 1, 4),
  ('Resolución', 'Trámite ante COMAR', 1, 5),
  ('Solicitud de TVRH', 'En paralelo', 2, 6),
  ('Amparo', 'En paralelo', 2, 7),
  ('Citas de entrega de tarjeta', 'En paralelo', 2, 8)
) as seed(name, group_name, group_order, step_order)
where template.practice_area = 'Migratorio/COMAR';

alter table public.case_stage_templates_v8 enable row level security;
alter table public.case_stage_steps_v8 enable row level security;
alter table public.client_case_stage_progress_v8 enable row level security;

create policy "Socios consultan plantillas procesales V8"
on public.case_stage_templates_v8 for select to authenticated
using ((select public.is_finance_partner()));

create policy "Socios consultan etapas procesales V8"
on public.case_stage_steps_v8 for select to authenticated
using ((select public.is_finance_partner()));

create policy "Socios consultan seguimiento procesal V8"
on public.client_case_stage_progress_v8 for select to authenticated
using ((select public.is_finance_partner()));

grant select on public.case_stage_templates_v8,
  public.case_stage_steps_v8,
  public.client_case_stage_progress_v8 to authenticated;
revoke all on public.case_stage_templates_v8,
  public.case_stage_steps_v8,
  public.client_case_stage_progress_v8 from anon;
revoke insert, update, delete on public.case_stage_templates_v8,
  public.case_stage_steps_v8,
  public.client_case_stage_progress_v8 from authenticated;

-- Un estado explícito permite que marcar y desmarcar sean idempotentes. La
-- función bloquea la ficha mientras valida el área y registra al socio actor.
create or replace function public.set_client_case_stage_v8(
  p_client_id bigint,
  p_step_id bigint,
  p_completed boolean
)
returns table (
  client_id bigint,
  step_id bigint,
  completed boolean,
  changed_at timestamptz,
  changed_by uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := (select auth.uid());
  v_client public.clients%rowtype;
  v_step public.case_stage_steps_v8%rowtype;
  v_template public.case_stage_templates_v8%rowtype;
  v_now timestamptz := now();
begin
  if v_actor is null or not exists (
    select 1 from public.partners p where p.user_id = v_actor
  ) then
    raise exception 'Tu cuenta no está autorizada para administrar la firma.';
  end if;
  if (select count(*) from public.partners) <> 2 then
    raise exception 'La firma debe conservar exactamente dos socios autorizados.';
  end if;
  if p_completed is null then
    raise exception 'Indica si la etapa está completada o pendiente.';
  end if;

  select c.* into v_client
  from public.clients c
  where c.id = p_client_id and c.deleted_at is null
  for update;
  if not found then
    raise exception 'El cliente ya no existe o está en la papelera.';
  end if;

  select s.* into v_step
  from public.case_stage_steps_v8 s
  where s.id = p_step_id;
  if not found then
    raise exception 'La etapa seleccionada no existe.';
  end if;

  select t.* into v_template
  from public.case_stage_templates_v8 t
  where t.id = v_step.template_id;

  if v_client.practice_area is distinct from v_template.practice_area then
    raise exception 'La etapa no corresponde al área de práctica del cliente.';
  end if;

  insert into public.client_case_stage_progress_v8 (
    client_id, step_id, completed, changed_at, changed_by
  ) values (
    p_client_id, p_step_id, p_completed, v_now, v_actor
  )
  on conflict on constraint client_case_stage_progress_v8_pkey do update
    set completed = excluded.completed,
        changed_at = excluded.changed_at,
        changed_by = excluded.changed_by;

  insert into public.finance_audit_log (
    entity, record_id, action, actor_id, snapshot
  ) values (
    'client',
    p_client_id,
    'updated',
    v_actor,
    jsonb_build_object(
      'v8_event', 'case_stage_changed',
      'practice_area', v_template.practice_area,
      'step_id', p_step_id,
      'step_name', v_step.name,
      'completed', p_completed,
      'changed_at', v_now
    )
  );

  return query
  select p.client_id, p.step_id, p.completed, p.changed_at, p.changed_by
  from public.client_case_stage_progress_v8 p
  where p.client_id = p_client_id and p.step_id = p_step_id;
end;
$$;

revoke all on function public.set_client_case_stage_v8(bigint, bigint, boolean)
  from public, anon;
grant execute on function public.set_client_case_stage_v8(bigint, bigint, boolean)
  to authenticated;

notify pgrst, 'reload schema';
commit;
