-- Esquema base. Después de ejecutarlo, aplica migration_integrity_v2.sql y
-- migration_product_v3.sql para activar socios, pagos, papelera e informes.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  kind text not null check (kind in ('Presupuesto','Recibo','Cuenta de cobro')),
  client_id bigint not null references public.clients(id) on delete restrict,
  concept text not null,
  amount_cents bigint not null check (amount_cents >= 0),
  status text not null default 'Pendiente' check (status in ('Pagado','Pendiente','Vencido','Aceptado')),
  notes text not null default '',
  issued_at timestamptz not null default now()
);

create table if not exists public.movements (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('Ingreso','Gasto')),
  category text not null,
  description text not null,
  amount_cents bigint not null check (amount_cents >= 0),
  document_id bigint references public.documents(id) on delete cascade,
  occurred_at timestamptz not null default now()
);

-- V3 permite varios abonos por documento; no debe existir un índice que limite
-- los ingresos vinculados a una sola fila.
drop index if exists public.one_income_per_document;

alter table public.clients enable row level security;
alter table public.documents enable row level security;
alter table public.movements enable row level security;

-- Este esquema base falla cerrado: no crea políticas permisivas. La migración
-- vigente crea la lista de socios y concede únicamente los accesos necesarios.
-- Estas sentencias también vuelven segura una reejecución accidental del archivo.
drop policy if exists "Socios administran clientes" on public.clients;
drop policy if exists "Socios administran documentos" on public.documents;
drop policy if exists "Socios administran movimientos" on public.movements;

grant usage, select on all sequences in schema public to authenticated;
