-- Esquema base. Después de ejecutarlo, aplica migration_integrity_v2.sql
-- para activar la lista de socios, transacciones, papelera y bitácora.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  kind text not null check (kind in ('Presupuesto','Recibo','Cuenta de cobro')),
  client_id bigint not null references public.clients(id) on delete restrict,
  concept text not null,
  amount_cents bigint not null check (amount_cents >= 0),
  status text not null default 'Pendiente' check (status in ('Pagado','Pendiente','Vencido','Aceptado')),
  notes text not null default '',
  issued_at timestamptz not null default now()
);

create table if not exists public.movements (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('Ingreso','Gasto')),
  category text not null,
  description text not null,
  amount_cents bigint not null check (amount_cents >= 0),
  document_id bigint references public.documents(id) on delete cascade,
  occurred_at timestamptz not null default now()
);

create unique index if not exists one_income_per_document on public.movements(document_id) where document_id is not null;

alter table public.clients enable row level security;
alter table public.documents enable row level security;
alter table public.movements enable row level security;

create policy "Socios administran clientes" on public.clients for all to authenticated using (true) with check (true);
create policy "Socios administran documentos" on public.documents for all to authenticated using (true) with check (true);
create policy "Socios administran movimientos" on public.movements for all to authenticated using (true) with check (true);

grant select, insert, update, delete on public.clients, public.documents, public.movements to authenticated;
grant usage, select on all sequences in schema public to authenticated;
